name: Validate Terraform Changes

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download Encrypted Artifact & Decrypt
        uses: badgerhobbs/terraform-state@v2
        with:
          encryption_key: ${{ secrets.AES_256_ENCRYPTION_KEY }}
          operation: download
          location: artifact
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0  # Specify your Terraform version

      - name: Check Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_dbt_account_id: ${{ secrets.TF_VAR_DBT_ACCOUNT_ID }}
          TF_VAR_dbt_token: ${{ secrets.TF_VAR_DBT_TOKEN }}
          TF_VAR_dbt_host_url: ${{ secrets.TF_VAR_DBT_HOST_URL }}