name: Validate Terraform Changes

on:
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Specify your Terraform version

    - name: Check Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_VAR_dbt_account_id: ${{ secrets.TF_VAR_dbt_account_id }}
        TF_VAR_dbt_token: ${{ secrets.TF_VAR_dbt_token }}
        TF_VAR_dbt_host_url: ${{ secrets.TF_VAR_dbt_host_url }}
